image:
  file: .gitpod/Dockerfile
tasks:
  - name: golang live
    init: |
      go install gotest.tools/gotestsum@latest
      go get && go build -o build/superiad
    command: |
      docker run --name="superiad" --rm -d -p 5432:5432 \
      -e POSTGRES_PASSWORD=superiad \
      -e POSTGRES_USER=superiad \
      -e POSTGRES_DB=superiad \
      postgres -c log_statement=all
      sleep 12
      gp sync-done db
      cp sample.env .env
      air
  
  - name: postgres shell
    command: |
      gp sync-await db
      docker exec -it superiad psql -U superiad
    
vscode:
  extensions:
    - golang.go